# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('total_perior', models.IntegerField()),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('department_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('school_year', models.CharField(max_length=30)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.CourseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=30)),
                ('sex', models.IntegerField()),
                ('major', models.CharField(max_length=30)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.ClassInfo')),
            ],
        ),
        migrations.CreateModel(
            name='teacher_course_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('school_year', models.CharField(max_length=30)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.ClassInfo')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.CourseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=30)),
                ('sex', models.IntegerField()),
                ('department_id', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='teacher_course_class',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.TeacherInfo'),
        ),
        migrations.AddField(
            model_name='student_course',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.StudentInfo'),
        ),
        migrations.AddField(
            model_name='class_course',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.ClassInfo'),
        ),
        migrations.AddField(
            model_name='class_course',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.CourseInfo'),
        ),
    ]
