# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='managers',
            fields=[
                ('man_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('man_name', models.CharField(max_length=30)),
                ('password', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='departmentinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='password',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='password',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='class_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.DepartmentInfo'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='department_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sex',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='stu_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.DepartmentInfo'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='sex',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='teacher_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='telephone',
            field=models.CharField(max_length=30),
        ),
    ]
