# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_auto_20160709_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.ClassInfo')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.CourseInfo')),
            ],
        ),
        migrations.RenameModel(
            old_name='managers',
            new_name='ManagersInfo',
        ),
        migrations.RenameModel(
            old_name='student_course',
            new_name='StudentCourse',
        ),
        migrations.RenameModel(
            old_name='teacher_course_class',
            new_name='TeacherCourseClass',
        ),
        migrations.RemoveField(
            model_name='class_course',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='class_course',
            name='course_id',
        ),
        migrations.DeleteModel(
            name='class_course',
        ),
    ]
