# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_auto_20160709_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcourse',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='classcourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='classinfo',
            name='department_id',
        ),
        migrations.DeleteModel(
            name='ManagersInfo',
        ),
        migrations.RemoveField(
            model_name='teachercourseclass',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='teachercourseclass',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='teachercourseclass',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='department_id',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='class_id',
            field=models.IntegerField(max_length=10),
        ),
        migrations.DeleteModel(
            name='ClassCourse',
        ),
        migrations.DeleteModel(
            name='ClassInfo',
        ),
        migrations.DeleteModel(
            name='DepartmentInfo',
        ),
        migrations.DeleteModel(
            name='TeacherCourseClass',
        ),
    ]
