# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0006_auto_20160710_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('class_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DdepartmentInfo',
            fields=[
                ('department_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.TeacherInfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.ClassInfo'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.DdepartmentInfo'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='department_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dataapp.DdepartmentInfo'),
        ),
    ]
