# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0007_auto_20160711_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.DdepartmentInfo'),
        ),
    ]
